<?php

/**
 * Implements hook_menu().
 */
function entityform_menu() {
  $items = array();

  $items['admin/structure/entityform-types'] = array(
    'title' => 'Entityform types',
    'description' => 'Manage entityform types, including default status, front page promotion, comment settings, etc.',
    'route_name' => 'entityform.overview_types',
  );
  $items['admin/structure/entityform-types/list'] = array(
    'title' => 'List',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/structure/entityform-types/add'] = array(
    'title' => 'Add entityform type',
    'route_name' => 'entityform.type_add',
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/structure/entityform-types/manage/%entityform_type'] = array(
    'title' => 'Edit entityform type',
    //'title callback' => 'entity_page_label',
    'title arguments' => array(4),
    'route_name' => 'entityform.type_edit',
  );
  $items['admin/structure/entityform-types/manage/%entityform_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}